# Generated by Django 5.2.3 on 2025-07-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
