# Generated by Django 5.2.3 on 2025-07-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel', '여행'), ('food', '맛집')], default='travel', max_length=20),
        ),
    ]
