# Generated by Django 5.2.3 on 2025-07-05 02:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_post_upload_path),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
